# Database Config - In memory Database
spring.datasource.url=jdbc:h2:mem:Estimatea;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver

# Credentials
spring.datasource.username=sa
spring.datasource.password=

# SQL initialisation
spring.sql.init.schema-locations=classpath:h2init.sql
spring.sql.init.data-locations=classpath:data-test.sql
spring.sql.init.mode=always
